### ISSUE TITLE
fail build when added workboxOpts

### ISSUE THREAD

**Issue by eldyvoon** [hanford/personal-website#1]
I added workboxOpts to use importScripts for firebase cloud messaging, 

```
module.exports = withOffline({
  workboxOpts: {
    runtimeCaching: [
      {
        urlPattern: /^https?.*/,
        handler: "networkFirst",
        importScripts: ["static/firebase-messanging-sw.js"],
        skipWaiting: true,
        clientsClaim: true
      }
    ]
  },
  webpack(config) {
    if (ANALYZE) {
      const opts = ANALYZE === 1 ? AnalyzeOpts : AnalyzeGetStats;

      config.plugins.push(new BundleAnalyzerPlugin(opts));
    }

    return config;
  }
});
```

but when I run `npm run build`, I got 

```{ ValidationError: child "runtimeCaching" fails because ["runtimeCaching" at position 0 fails because ["importScripts" is not a supported parameter., "skipWaiting" is not a supported parameter., "clientsClaim" is not a supported parameter.]] ``` 

What's the problem? I'm stuck trying to implement this simple push notification https://github.com/Leocardoso94/push-notification-demo into nextjs, any thought?

**Comment by hanford** [comment]
@eldyvoon at a glance it looks like you're workbox config is incorrect.

[See their documentation](https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#configuration)

I think it should be

```js
  workboxOpts: {
    importScripts: ["static/firebase-messanging-sw.js"],
    skipWaiting: true,
    clientsClaim: true
    runtimeCaching: [
      {
        urlPattern: /^https?.*/,
        handler: "networkFirst",
      }
    ]
  },
```

**Comment by hanford** [comment]
Going to close, I don't think is an issue with `next-offline` or my personal website.
