### ISSUE TITLE
Not working PWA properly without Now

### ISSUE THREAD

**Issue by findelallc** [hanford/personal-website#3]
Hi @hanford can you little help how I can modify and host your solution without Now(Zeit),as my server is completely on AWS. I didn't get much solution about pwa tutorial with NEXT.js or even with next-offline package?

**Comment by hanford** [comment]
Hmmm, can you explain a little bit more? Is this issue with my personal website or next-offline? or both?

**Comment by findelallc** [comment]
Thanks @hanford, the problem is with the next-offline package to integrate on AWS for non serverless not your site(which is real damn good), but this [package](https://github.com/shadowwalker/next-pwa) also helps us to do for non Now(Zeit) project.

**Comment by hanford** [comment]
Thanks! Have you tried this part of the README?

https://github.com/hanford/next-offline#now-10

**Comment by findelallc** [comment]
yeah! I tried to follow,but documentation was not as easy to follow,anyways thanks.
