### ISSUE TITLE
Missing service-worker.js

### ISSUE THREAD

**Issue by Yilong94** [hanford/personal-website#8]
Hi @hanford, I am relatively new to service-worker and happened to chance upon your project on `next-offline`, as well as your personal project which is a PWA which are really great. 

However, I was looking through the project directories and realised that the project does not seem to contain a `service-worker.js` file. I understand `next-offline` automatically registers the service worker at compile time but I am just a little confused whether the service worker file is created by `next-offline` or is that handled by workbox? Thanks!

**Comment by hanford** [comment]
It's handled by workbox/next-offline, that automatically creates the service worker at compile time
